#!/bin/bash
# test-locking.sh
# Tests that file locking works correctly for concurrent updates

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
UPDATE_SCRIPT="${SCRIPT_DIR}/update-health-dashboard.sh"
DASHBOARD_PATH="${SCRIPT_DIR}/agent-health.md"
LOCK_DIR="/tmp/agent-health-dashboard.lock"
BACKUP_PATH="/tmp/agent-health-backup-lock.md"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0

pass() {
    echo -e "${GREEN}✓ PASS:${NC} $1"
    TESTS_PASSED=$((TESTS_PASSED + 1))
}

fail() {
    echo -e "${RED}✗ FAIL:${NC} $1"
    TESTS_FAILED=$((TESTS_FAILED + 1))
}

# Backup original dashboard
if [ -f "$DASHBOARD_PATH" ]; then
    cp "$DASHBOARD_PATH" "$BACKUP_PATH"
fi

# Cleanup function
cleanup() {
    if [ -f "$BACKUP_PATH" ]; then
        mv "$BACKUP_PATH" "$DASHBOARD_PATH"
    fi
    rm -rf "$LOCK_DIR"
    rm -f /tmp/LockTestAgent-uptime-start
    rm -f /tmp/ConcurrentAgent1-uptime-start
    rm -f /tmp/ConcurrentAgent2-uptime-start
    rm -f /tmp/ConcurrentAgent3-uptime-start
}
trap cleanup EXIT

# Helper: acquire lock using mkdir
acquire_test_lock() {
    mkdir "$LOCK_DIR" 2>/dev/null
}

# Helper: release lock
release_test_lock() {
    rm -rf "$LOCK_DIR" 2>/dev/null
}

echo "=== Testing File Locking ==="
echo ""

# Test 1: Lock file is used
echo "Test 1: Lock file exists after update"
rm -rf "$LOCK_DIR"

export MODEL="lock-test"
export CHANNEL="test"
"$UPDATE_SCRIPT" "LockTestAgent" "LockTest" 2>/dev/null || true

# Lock file may or may not persist after script, check that script completed
if grep -q "LockTestAgent" "$DASHBOARD_PATH"; then
    pass "Update completed successfully"
else
    fail "Update did not complete"
fi

# Test 2: Concurrent updates don't corrupt file
echo ""
echo "Test 2: Concurrent updates don't corrupt dashboard"

# Create a fresh dashboard
cat > "$DASHBOARD_PATH" << 'EOF'
# Agent Health Dashboard

**Last Updated:** 2026-02-13T10:00:00 EST
**Version:** 1

---

## Status Legend
- 🟢 Healthy — Last ping < 30 min
- 🟡 Warning — Last ping 30-60 min
- 🔴 Critical — Last ping > 60 min
- ⚪ Unknown — No data

---

*Auto-generated by agent heartbeats.*
EOF

# Run multiple updates concurrently
export MODEL="concurrent-test"
export CHANNEL="test"

(
    for i in {1..5}; do
        "$UPDATE_SCRIPT" "ConcurrentAgent1" "Test1" 2>/dev/null &
    done
    wait
) 2>/dev/null || true

(
    for i in {1..5}; do
        "$UPDATE_SCRIPT" "ConcurrentAgent2" "Test2" 2>/dev/null &
    done
    wait
) 2>/dev/null || true

(
    for i in {1..5}; do
        "$UPDATE_SCRIPT" "ConcurrentAgent3" "Test3" 2>/dev/null &
    done
    wait
) 2>/dev/null || true

# Give time for all processes to complete
sleep 2

# Check dashboard is valid markdown and contains expected content
if grep -q "# Agent Health Dashboard" "$DASHBOARD_PATH"; then
    pass "Dashboard header preserved"
else
    fail "Dashboard header corrupted"
fi

# Check for single occurrence of each agent (no duplicates)
AGENT1_COUNT=$(grep -c "## ConcurrentAgent1" "$DASHBOARD_PATH" 2>/dev/null || echo "0")
AGENT2_COUNT=$(grep -c "## ConcurrentAgent2" "$DASHBOARD_PATH" 2>/dev/null || echo "0")
AGENT3_COUNT=$(grep -c "## ConcurrentAgent3" "$DASHBOARD_PATH" 2>/dev/null || echo "0")

if [ "$AGENT1_COUNT" -le 1 ] && [ "$AGENT2_COUNT" -le 1 ] && [ "$AGENT3_COUNT" -le 1 ]; then
    pass "No duplicate agent sections (locking prevented corruption)"
else
    echo "Agent1: $AGENT1_COUNT, Agent2: $AGENT2_COUNT, Agent3: $AGENT3_COUNT"
    fail "Duplicate sections detected - locking may not be working"
fi

# Test 3: Manual lock blocks update (simulated)
echo ""
echo "Test 3: Lock prevents concurrent writes"

# Create a lock directory
if acquire_test_lock; then
    # Try to update (should succeed or skip gracefully due to lock)
    OUTPUT=$("$UPDATE_SCRIPT" "LockTestAgent2" "LockTest" 2>&1 || true)

    # Release lock
    release_test_lock

    # Script should either complete or skip gracefully
    pass "Update handled locked file gracefully"
else
    fail "Could not acquire test lock"
fi

# Test 4: Lock is released after update
echo ""
echo "Test 4: Lock released after update"

# Run update
"$UPDATE_SCRIPT" "FinalAgent" "Final" 2>/dev/null || true

# Try to acquire lock immediately after
sleep 1
if acquire_test_lock; then
    release_test_lock
    pass "Lock released after update"
else
    fail "Lock still held after update"
fi

# Summary
echo ""
echo "=== Test Summary ==="
echo -e "Passed: ${GREEN}${TESTS_PASSED}${NC}"
echo -e "Failed: ${RED}${TESTS_FAILED}${NC}"

if [ "$TESTS_FAILED" -eq 0 ]; then
    echo -e "${GREEN}All tests passed!${NC}"
    exit 0
else
    echo -e "${RED}Some tests failed.${NC}"
    exit 1
fi
